const DESTINATIONS=[{id:"perry-high-school-target",name:"Point me to Perry High School",lat:33.261382,lon:-111.747406}];
const METERS_PER_MILE=1609.344,FEET_PER_METER=3.28084,FEET_SWITCHOVER=2640,ARRIVAL_RADIUS_METERS=9.144;
const targetName=document.querySelector("#targetName"),distanceValue=document.querySelector("#distanceValue"),helperText=document.querySelector("#helperText"),startButton=document.querySelector("#startButton"),needle=document.querySelector("#needle");
let selectedTarget=DESTINATIONS[0],currentPosition=null,currentHeading=0,hasHeading=false,watchId=null,needleRotation=0,hasArrived=false;
function toRadians(degrees){return degrees*(Math.PI/180)}
function toDegrees(radians){return radians*(180/Math.PI)}
function normalizeDegrees(degrees){return((degrees%360)+360)%360}
function shortestRotationDelta(fromDegrees,toDegrees){return((toDegrees-fromDegrees+540)%360)-180}
function distanceMeters(from,to){const earthRadiusMeters=6371008.8,lat1=toRadians(from.lat),lat2=toRadians(to.lat),deltaLat=toRadians(to.lat-from.lat),deltaLon=toRadians(to.lon-from.lon),a=Math.sin(deltaLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(deltaLon/2)**2;return earthRadiusMeters*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function bearingDegrees(from,to){const lat1=toRadians(from.lat),lat2=toRadians(to.lat),deltaLon=toRadians(to.lon-from.lon),y=Math.sin(deltaLon)*Math.cos(lat2),x=Math.cos(lat1)*Math.sin(lat2)-Math.sin(lat1)*Math.cos(lat2)*Math.cos(deltaLon);return normalizeDegrees(toDegrees(Math.atan2(y,x)))}
function formatDistance(meters){const feet=meters*FEET_PER_METER;if(feet<FEET_SWITCHOVER){return`${Math.round(feet).toLocaleString()} ft`}const miles=meters/METERS_PER_MILE;return`${miles>=10?miles.toFixed(1):miles.toFixed(2)} mi`}
function getCompassHeading(event){if(typeof event.webkitCompassHeading==="number"){return event.webkitCompassHeading}if(typeof event.alpha==="number"){return normalizeDegrees(360-event.alpha)}return null}
function maybeOpenArrival(distance){if(hasArrived||distance>ARRIVAL_RADIUS_METERS){return}hasArrived=true;distanceValue.textContent="0 ft";window.location.assign("arrival.html")}
function render(){targetName.textContent=selectedTarget.name;if(!currentPosition){needleRotation=0;needle.style.transform="translate(-50%, -100%) rotate(0deg)";return}const distance=distanceMeters(currentPosition,selectedTarget),bearing=bearingDegrees(currentPosition,selectedTarget),relativeBearing=normalizeDegrees(bearing-(hasHeading?currentHeading:0)),currentNormalizedRotation=normalizeDegrees(needleRotation),rotationDelta=shortestRotationDelta(currentNormalizedRotation,relativeBearing);needleRotation+=rotationDelta;distanceValue.classList.remove("is-waiting");distanceValue.textContent=formatDistance(distance);needle.style.transform=`translate(-50%, -100%) rotate(${needleRotation}deg)`;maybeOpenArrival(distance)}
async function requestOrientationPermission(){if(typeof DeviceOrientationEvent!=="undefined"&&typeof DeviceOrientationEvent.requestPermission==="function"){const result=await DeviceOrientationEvent.requestPermission();if(result!=="granted"){throw new Error("Compass permission was not granted.")}}}
function startLocationWatch(){if(!navigator.geolocation){throw new Error("This browser does not support GPS location.")}if(watchId!==null){navigator.geolocation.clearWatch(watchId)}watchId=navigator.geolocation.watchPosition(position=>{currentPosition={lat:position.coords.latitude,lon:position.coords.longitude};render()},error=>{distanceValue.textContent="Location blocked";distanceValue.classList.add("is-waiting");helperText.textContent=error.message||"Allow location access to use the compass.";startButton.disabled=false;startButton.textContent="Start compass";startButton.classList.remove("is-live")},{enableHighAccuracy:true,maximumAge:2000,timeout:12000})}
async function startCompass(){startButton.disabled=true;startButton.textContent="Starting...";try{await requestOrientationPermission();window.addEventListener("deviceorientation",handleOrientation,true);window.addEventListener("deviceorientationabsolute",handleOrientation,true);startLocationWatch();startButton.textContent="Compass active";startButton.classList.add("is-live");helperText.textContent="Keep the phone flat and rotate your body until the needle points straight up."}catch(error){startButton.disabled=false;startButton.textContent="Start compass";distanceValue.textContent="Permission needed";distanceValue.classList.add("is-waiting");helperText.textContent=error.message||"Allow GPS and motion access to continue."}}
function handleOrientation(event){const heading=getCompassHeading(event);if(heading===null){return}currentHeading=heading;hasHeading=true;render()}
startButton.addEventListener("click",startCompass);render();
